fix clang high version build aosp kernel error
ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - __stack_chk_guard
Symbols missing from symbol list: